More robust tests

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -142,20 +142,45 @@ jobs:
       - name: Import image
         run: |
           docker load --input ci-${{ matrix.arch }}-${{ github.run_number }}.tar.gz
+          docker tag ci:${{ github.run_number }} ci:latest
 
-      # Run test twice to see if restarts persist data
-      - name: Run image
+      # Fails if zoneminder is not up
+      - name: Start image twice
+        timeout-minutes: 5
         run: |
           set -x
-          docker tag ci:${{ github.run_number }} ci:latest
+          docker-compose -f docker-compose.test.yml up &
+          sleep 60
+          if [ ! "$(docker ps -q -f name=zoneminder)" ]; then
+              exit 1
+          fi
+          docker-compose -f docker-compose.test.yml down
+          docker-compose -f docker-compose.test.yml up &
+          sleep 60
+          docker-compose -f docker-compose.test.yml down
+
+      # Fails if zoneminder fails to stop normally
+      - name: Start image and stop zoneminder
+        timeout-minutes: 5
+        run: |
+          set -x
           docker-compose -f docker-compose.test.yml up &
           sleep 60
           docker stop zoneminder
           docker-compose -f docker-compose.test.yml down
+
+      # Fails if zoneminder doesn't stop when db is down
+      - name: Start image and stop db
+        timeout-minutes: 5
+        run: |
+          set -x
           docker-compose -f docker-compose.test.yml up &
           sleep 60
-          docker stop zoneminder
-          docker-compose -f docker-compose.test.yml down
+          docker stop db
+          sleep 10
+          if [ "$(docker ps -q -f name=zoneminder)" ]; then
+              exit 1
+          fi
 
   release:
     needs:
